# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
publish_target_min=1.21.1
publish_target_max=1.21.1
git_branch=master

# Mod Properties
mod_version=0.2.1
maven_group=dev.enjarai
mod_modrinth=zQqsEeqy
mod_curseforge=1006270
mod_github=enjarai/rolling-down-in-the-deep

# Dependencies
fabric_version=0.100.7+1.21
do_a_barrel_roll_version=3.7.3+1.21-neoforge
# https://github.com/isXander/YetAnotherConfigLib/releases
yacl_version=3.8.0+1.21.1-neoforge
